version: "3"

networks:
  cross-http-net:
    driver: bridge

services:
  bank-gateway:
    image: 'yevgenykcx/bank-gateway:latest'
    networks:
      - cross-http-net
    ports:
      - '8110:8110'
    environment:
      - BANK_ANALYSIS_URL=http://bank-analysis:8111
      - BANK_STORAGE_URL=http://bank-storage:8112
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure

  bank-analysis:
    image: 'yevgenykcx/bank-analysis:latest'
    networks:
      - cross-http-net
    ports:
      - '8111:8111'
    environment:
      - JAVA_HTTP_ENTRY_POINT_URL=http://bank-gateway:8110
      - BANK_STORAGE_URL=http://bank-storage:8112
      - NET_CORE_REST_ENTRY_POINT_EXAMPLE_URL=http://dotnet-core-http-entry-point:5551
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure

  dotnet-core-http-entry-point:
    image: 'yevgenykcx/dotnet-core-http-entry-point'
    networks:
      - cross-http-net
    ports:
      - '5551:5551'
    environment:
      - NET_CORE_PROPOGATOR_EXAMPLE_URL=http://dotnet-core-http-propagator:5552
      - NET_CORE_SINK_EXAMPLE_URL=http://dotnet-core-http-sink:5553
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure

  dotnet-core-http-propagator:
    image: 'yevgenykcx/dotnet-core-http-propagator'
    networks:
      - cross-http-net
    ports:
      - '5552:5552'
    environment:
      - NET_CORE_REST_ENTRY_POINT_EXAMPLE_URL=http://dotnet-core-http-entry-point:5551
      - NET_CORE_SINK_EXAMPLE_URL=http://dotnet-core-http-sink:5553
      - NODEJS_REST_ENTRY_POINT_EXAMPLE_URL=http://node-http-entry-point:5010
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    # workaround for concurrent IAST agent download bug:
    restart: on-failure
   
  mysql:
    image: mysql:5
    networks:
      - cross-http-net
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    expose:
      - "3306"

  node-http-entry-point:
    image: 'yevgenykcx/node-http-entry-point'
    networks:
      - cross-http-net
    ports:
      - '5010:5010'
    environment:
      - NODEJS_REST_PROPAGATOR_EXAMPLE_URL=http://node-http-propagator:5011
      - NODEJS_REST_SINK_EXAMPLE_URL=http://node-http-sink:5012
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    restart: on-failure
    
  node-http-propagator:
    image: 'yevgenykcx/node-http-propagator'
    networks:
      - cross-http-net
    ports:
      - '5011:5011'
    environment:
      - NODEJS_REST_ENTRY_POINT_EXAMPLE_URL=http://node-http-entry-point:5010
      - NODEJS_REST_SINK_EXAMPLE_URL=http://node-http-sink:5012
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
    restart: on-failure
    
  node-http-sink:
    image: 'yevgenykcx/node-http-sink'
    networks:
      - cross-http-net
    ports:
      - '5012:5012'
    environment:
      - NODEJS_REST_ENTRY_POINT_EXAMPLE_URL=http://node-http-entry-point:5010
      - NODEJS_REST_PROPAGATOR_EXAMPLE_URL=http://node-http-propagator:5011
      - IAST_MANAGER_URL=${IAST_MANAGER_URL}
      - MYSQL_URL=mysql
    restart: on-failure
