name: .NET Core CD

on:
  push:
    branches:
      - master
    paths:
      - 'dotnet-core-apps/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: dotnet-core-apps

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Deploy NET_CORE_PROPOGATOR_APP
        uses: docker/build-push-action@v2
        with:
          context: ./dotnet-core-apps/NET_CORE_PROPOGATOR_APP
          file: ./dotnet-core-apps/NET_CORE_PROPOGATOR_APP/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/net-core-propogator-app:latest
      - name: Deploy NET_CORE_REST_ENTRY_POINT_APP
        uses: docker/build-push-action@v2
        with:
          context: ./dotnet-core-apps/NET_CORE_REST_ENTRY_POINT_APP
          file: ./dotnet-core-apps/NET_CORE_REST_ENTRY_POINT_APP/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/net-core-rest-entry-point-app:latest
      - name: Deploy NET_CORE_SINK_APP
        uses: docker/build-push-action@v2
        with:
          context: ./dotnet-core-apps/NET_CORE_SINK_APP
          file: ./dotnet-core-apps/NET_CORE_SINK_APP/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/net-core-sink-app:latest
